### PR TITLE
Speed up build

### PR DESCRIPTION
**Pull request by akitaSummer**
On my PC, the previous build speed was 4m5s, the current build speed is 40s.
You can run yarn start to test this.

### CODE REVIEW

**Comment by AGDholo** [comment]
I agree with using esbuild

**Comment by AGDholo** [comment]
`yarn build` failed with my local dev, this is a problem?

CI build same error: https://github.com/Hedgehog-Computing/hedgehog-lab/pull/86/checks?check_run_id=1864715315

**Comment by akitaSummer** [comment]
I've fixed the build errors.
You can run yarn build to test this.
If there are no problems, merge this pr for subsequent updates.
@lidangzzz @AGDholo

**Review by lidangzzz — APPROVED** [review]
Great job for speedup with esbuild! Thanks!

**Pull request merged**
