### PR TITLE
add docker file

### PR DESCRIPTION
**Pull request by t-lou**
Docker file based on debian for easier deployment

preferred entry: docker run -p 3000:3000 hedgehog-lab sh /opt/run.sh

### CODE REVIEW

**Comment by t-lou** [comment]
> According to [Offical Node Image from Docker Hub](https://hub.docker.com/_/node), maybe this will be more efficient if use `18-bullseye` and start from there? Probably should seperate all commands to multiple RUN as well.

I tried both node:18-bullseye and node:18-bullseye-slim, besides the need-to-be-overridden entry point, many other packages need to be installed, including xorg. I think in this case, using debian and node bases have little difference. How do you think?

Refactored the dockerfile to be more structured. Still prefer to have fewer layers.

**Comment by AGDholo** [comment]
Hi @t-lou,
Thanks for your PR 
xorg is necessary? We are just a static react site project, why should we need it?

**Comment by t-lou** [comment]
I neither, during the command "yarn install" in phase 4 it asked for x11, xi or {another lib, which I forget}. X11 is basically xorg. When I tried to install libxi-dev, it asked for _<GL/glx.h>_.

Thus I assume _node_ docker would not be a better solution.

**Comment by AGDholo** [comment]
Okay, it might be because of the 'ml-x' package in hlab-core.
And the last question, Why we need to specify a port when the project started?

**Comment by t-lou** [comment]
I remember seeing a question from email notification. So we need the port to connect the browser in host system and the program in docker container.

**Pull request merged**
