### PR TITLE
feat: syntax highlight in markdown

### PR DESCRIPTION
**Pull request by odysa**
Current preview of code is plain text.
image

With syntax highlight:
image

check out more styles -> [theme](https://react-syntax-highlighter.github.io/react-syntax-highlighter/demo/prism.html)

### CODE REVIEW

**Comment by AGDholo** [comment]
Looks good, I'm resolving the conflicts and try to merge it.

**Comment by AGDholo** [comment]
Looks good, could you pull the latest code and resolve conflicts?

**Comment by AGDholo** [comment]
Our team is considering using MDX to render markdown, which can be used as a feature request.

**Review by Himself65 — APPROVED** [review]
LGTM if resolve the conflict.

**Comment by odysa** [comment]
conflict resolved, but I think the snippet style should be different in light and dark mode.

**Comment by AGDholo** [comment]
How about the global dark theme?
image

cc @Himself65 @akitaSummer

**Comment by odysa** [comment]
> How about the global markdown dark theme? image
> 
> image
> 
> cc @Himself65 @akitaSummer

I believe it is better to be consistent in styles, which means the style of syntax changes accordingly.

**Comment by AGDholo** [comment]
All transparent:
image
image

**Comment by AGDholo** [comment]
Thanks for your contribution, currently PR is merged.

**Pull request merged**
