### PR TITLE
Refactor: refactor upload and save button

### LINKED ISSUE #82: UI suggestion on Upload and Save buttons
**Is your feature request related to a problem? Please describe.**
Current "upload" and "save" buttons are confusing to me. Those buttons are to upload a new file to the YouCode session or save YouCode session into a local file. But they are placed inside the sidebar, which feel unrelated to YouCode session.

**Describe the solution you'd like**
Re-position two buttons from sidebar to YouCode session. Replace them with icons to avoid information overload. By doing so, customers have a clear understanding on both upload and save actions are related to YouCode session. Actually upload can be considered as "Open a new file", so open can be the alternative name for that button.

I am happy to do the code change once we anchor down the details.

**Additional context**
The left icon is for uploading a file into YouCode session and the right icon is to save current YouCode session into a local file.
截屏2020-11-07 下午4 22 02

### PR DESCRIPTION
**Pull request by akitaSummer**
Fixes #82 

I think we should add a bulletin board to show people what we've updated.When you update the version or update the teaching video, you only need to updated the .md file.

If you think it's useful, I'll make this feature in the near future.

### CODE REVIEW

**Comment by AGDholo** [comment]
#78 
The draft is not great. I've looked at other open source projects and it looks like there should be a way to automatically crawl PR and output updates.

**Comment by akitaSummer** [comment]
What if we write a node script file to use in Git hooks

This node script file creates or updated a json file after each commit to get the commit content, then hedgehog-lab can use react components to automatically read json files and display them to bulletin boards.

**Comment by akitaSummer** [comment]
hi, I write a node script file to use in Git hooks, the address is https://github.com/akitaSummer/gitCommitTest.

When your commit message starts is ‘doc:’, it automatically generates a JSON file.

doc:version: 1.0.3,description: test -> {"version":"1.0.3","description":"test"}

How about this draft, we can use the automatically generated JSON file to update the bulletin board.

Can this PR be merged?

@AGDholo @lidangzzz

**Comment by AGDholo** [comment]
#97 
I open a PR to resolve it, and the changelog module needs open a new PR I guess.

**Pull request closed without merging**
